const teamMembers = [
    {
        photo: "https://images.wikidexcdn.net/mwuploads/wikidex/thumb/0/0b/latest/20160904204605/Snorlax.png/800px-Snorlax.png",
        name: "Alonzo Perez",
        github: "https://github.com/",
        linkedin: "https://www.linkedin.com/",
    },
    {
        photo: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
        name: "Dante Vásquez",
        github: "https://github.com/jdantevc",
        linkedin: "https://www.linkedin.com/in/jdantevc/",
    },
    {
        photo: "https://images.wikidexcdn.net/mwuploads/wikidex/thumb/f/fb/latest/20200411222755/Charmeleon.png/800px-Charmeleon.png",
        name: "Jimmy Cahuas",
        github: "https://github.com/",
        linkedin: "https://www.linkedin.com/",
    },
    {
        photo: "https://www.latercera.com/resizer/qBNTRKQWHm26rezD6oUGqSqBMic=/900x600/smart/cloudfront-us-east-1.images.arcpublishing.com/copesa/KCV3Q7JXTBEMVAJVBDONB6YIFE.png",
        name: "Jorge Capcha",
        github: "https://github.com/",
        linkedin: "https://www.linkedin.com/",
    },
    {
        photo: "https://images.wikidexcdn.net/mwuploads/wikidex/thumb/2/20/latest/20230613020138/Gligar.png/1200px-Gligar.png",
        name: "Jorge Estrada",
        github: "https://github.com/",
        linkedin: "https://www.linkedin.com/",
    },
    {
        photo: "https://images.wikidexcdn.net/mwuploads/wikidex/thumb/a/af/latest/20150110232910/Jigglypuff.png/800px-Jigglypuff.png",
        name: "Laura Lugo",
        github: "https://github.com/",
        linkedin: "https://www.linkedin.com/",
    },
];

const datafake = [
    {
        id: 11,
        rent_value: 4996,
        bedrooms: 3,
        bathrooms: 2,
        property_type: "apartment",
        address: "Suite 634 93891 Gutmann Port, Konopelskifurt, AZ 53949",
        area: "94",
        created_at: "2023-10-13T20:33:43.158Z",
        description: "Provident itaque error dolorem.",
        is_active: false,
        latitude: null,
        longitude: null,
        maintenance_price: 433,
        operation_type: "sale",
        pet_friendly: false,
        property_price: 413575,
        updated_at: "2023-10-13T20:33:43.158Z",
        urls: [
            "https://img.freepik.com/fotos-premium/moderna-acog…stacionamiento-generado-ai_859483-3864.jpg?w=2000",
        ],
        user_id: 20,
    },
    {
        id: 12,
        rent_value: 4500,
        bedrooms: 2,
        bathrooms: 1,
        property_type: "apartment",
        address: "123 Main St, Anytown, USA",
        area: "80",
        created_at: "2023-10-14T10:15:20.123Z",
        description: "Cozy apartment with great view.",
        is_active: true,
        latitude: 40.7128,
        longitude: -74.006,
        maintenance_price: 300,
        operation_type: "rent",
        pet_friendly: true,
        property_price: 300000,
        updated_at: "2023-10-14T10:15:20.123Z",
        urls: ["https://example.com/apartment-image.jpg"],
        user_id: 21,
    },
    {
        id: 11,
        rent_value: 4996,
        bedrooms: 3,
        bathrooms: 2,
        property_type: "apartment",
        address: "Suite 634 93891 Gutmann Port, Konopelskifurt, AZ 53949",
        area: "94",
        created_at: "2023-10-13T20:33:43.158Z",
        description: "Provident itaque error dolorem.",
        is_active: false,
        latitude: null,
        longitude: null,
        maintenance_price: 433,
        operation_type: "sale",
        pet_friendly: false,
        property_price: 413575,
        updated_at: "2023-10-13T20:33:43.158Z",
        urls: [
            "https://img.freepik.com/fotos-premium/moderna-acog…stacionamiento-generado-ai_859483-3864.jpg?w=2000",
        ],
        user_id: 20,
    },
    {
        id: 12,
        rent_value: 4500,
        bedrooms: 2,
        bathrooms: 1,
        property_type: "apartment",
        address: "123 Main St, Anytown, USA",
        area: "80",
        created_at: "2023-10-14T10:15:20.123Z",
        description: "Cozy apartment with great view.",
        is_active: true,
        latitude: 40.7128,
        longitude: -74.006,
        maintenance_price: 300,
        operation_type: "rent",
        pet_friendly: true,
        property_price: 300000,
        updated_at: "2023-10-14T10:15:20.123Z",
        urls: ["https://example.com/apartment-image.jpg"],
        user_id: 21,
    },
];

const singleProperty = {
    id: 11,
    rent_value: 4996,
    bedrooms: 3,
    bathrooms: 2,
    property_type: "apartment",
    address: "Suite 634 93891 Gutmann Port, Konopelskifurt, AZ 53949",
    area: "94",
    created_at: "2023-10-13T20:33:43.158Z",
    description: "Provident itaque error dolorem.",
    is_active: false,
    latitude: null,
    longitude: null,
    maintenance_price: 433,
    operation_type: "sale",
    pet_friendly: false,
    property_price: 413575,
    updated_at: "2023-10-13T20:33:43.158Z",
    urls: [
        "https://img.freepik.com/fotos-premium/moderna-acog…stacionamiento-generado-ai_859483-3864.jpg?w=2000",
    ],
    user_id: 20,
};

export { teamMembers, datafake, singleProperty };
