import alonsoUrl from "/src/assets/team06.jpg"
import danteUrl from "/src/assets/team04.jpg"
import jimmyUrl from "/src/assets/team03.jpg"
import jorgeCapUrl from "/src/assets/team02.jpg"
import jorgeEsUrl from "/src/assets/team01.jpg"
import lauUrl from "/src/assets/team05.jpg"

const teamMembers = [
    {
        photo: alonsoUrl,
        name: "Alonzo Perez",
        github: "https://github.com/Alonzzoh",
        linkedin: "https://www.linkedin.com/in/alonsoperezp/",
    },
    {
        photo: danteUrl,
        name: "Dante Vásquez",
        github: "https://github.com/jdantevc",
        linkedin: "https://www.linkedin.com/in/jdantevc/",
    },
    {
        photo: jimmyUrl,
        name: "Jimmy Cahuas",
        github: "https://github.com/Alyhoiz",
        linkedin: "https://www.linkedin.com/in/jim-alyhoiz/",
    },
    {
        photo: jorgeCapUrl,
        name: "Jorge Capcha",
        github: "https://github.com/Kamaqen",
        linkedin: "https://www.linkedin.com/in/jorgecapcha/",
    },
    {
        photo: jorgeEsUrl,
        name: "Jorge Estrada",
        github: "https://github.com/IIJorgeEstradaII",
        linkedin: "https://www.linkedin.com/in/22jorge-estrada/",
    },
    {
        photo: lauUrl,
        name: "Laura Lugo",
        github: "https://github.com/iamlaudew",
        linkedin: "https://www.linkedin.com/in/iamlaudew/",
    },
];

const datafake = [
    {
        id: 11,
        rent_value: 4996,
        bedrooms: 3,
        bathrooms: 2,
        property_type: "department",
        address: "Suite 634 93891 Gutmann Port, Konopelskifurt, AZ 53949",
        area: "94",
        created_at: "2023-10-13T20:33:43.158Z",
        description: "Provident itaque error dolorem.",
        is_active: false,
        latitude: null,
        longitude: null,
        maintenance_price: 433,
        operation_type: "sale",
        pet_friendly: false,
        property_price: 413575,
        updated_at: "2023-10-13T20:33:43.158Z",
        urls: [
            "https://img.freepik.com/fotos-premium/moderna-acog…stacionamiento-generado-ai_859483-3864.jpg?w=2000",
        ],
        user_id: 20,
    },
    {
        id: 12,
        rent_value: 4500,
        bedrooms: 2,
        bathrooms: 1,
        property_type: "apartment",
        address: "123 Main St, Anytown, USA",
        area: "80",
        created_at: "2023-10-14T10:15:20.123Z",
        description: "Cozy apartment with great view.",
        is_active: true,
        latitude: 40.7128,
        longitude: -74.006,
        maintenance_price: 300,
        operation_type: "rent",
        pet_friendly: true,
        property_price: 300000,
        updated_at: "2023-10-14T10:15:20.123Z",
        urls: ["https://example.com/apartment-image.jpg"],
        user_id: 21,
    },
    {
        id: 11,
        rent_value: 4996,
        bedrooms: 3,
        bathrooms: 2,
        property_type: "department",
        address: "Suite 634 93891 Gutmann Port, Konopelskifurt, AZ 53949",
        area: "94",
        created_at: "2023-10-13T20:33:43.158Z",
        description: "Provident itaque error dolorem.",
        is_active: false,
        latitude: null,
        longitude: null,
        maintenance_price: 433,
        operation_type: "sale",
        pet_friendly: false,
        property_price: 413575,
        updated_at: "2023-10-13T20:33:43.158Z",
        urls: [
            "https://img.freepik.com/fotos-premium/moderna-acog…stacionamiento-generado-ai_859483-3864.jpg?w=2000",
        ],
        user_id: 20,
    },
    {
        id: 12,
        rent_value: 4500,
        bedrooms: 2,
        bathrooms: 1,
        property_type: "apartment",
        address: "123 Main St, Anytown, USA",
        area: "80",
        created_at: "2023-10-14T10:15:20.123Z",
        description: "Cozy apartment with great view.",
        is_active: true,
        latitude: 40.7128,
        longitude: -74.006,
        maintenance_price: 300,
        operation_type: "rent",
        pet_friendly: true,
        property_price: 300000,
        updated_at: "2023-10-14T10:15:20.123Z",
        urls: ["https://example.com/apartment-image.jpg"],
        user_id: 21,
    },
];

const singleProperty = {
    id: 11,
    rent_value: 4996,
    bedrooms: 3,
    bathrooms: 2,
    property_type: "department",
    address: "Suite 634 93891 Gutmann Port, Konopelskifurt, AZ 53949",
    area: "94",
    created_at: "2023-10-13T20:33:43.158Z",
    description: "Provident itaque error dolorem.",
    is_active: false,
    latitude: null,
    longitude: null,
    maintenance_price: 433,
    operation_type: "sale",
    pet_friendly: false,
    property_price: 413575,
    updated_at: "2023-10-13T20:33:43.158Z",
    urls: [
        "https://img.freepik.com/fotos-premium/moderna-acog…stacionamiento-generado-ai_859483-3864.jpg?w=2000",
    ],
    user_id: 20,
};

export { teamMembers, datafake, singleProperty };
